language: ruby
rvm:
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - ruby-head
  - jruby-head
before_install: gem install bundler -v 1.10.6
addons:
  code_climate:
    repo_token: 791e0a47aac4a5af442e2b73997420fec04c577c46bf8cba1af28351f1a57666
